import pygame
import pygame.locals

#bg
unscroll_bg = pygame.image.load("assets/images/bg/bg.jpg")

#buttons
start_img = pygame.image.load("assets/images/buttons/placeholder_button.png").convert_alpha()
startdown_img = pygame.image.load("assets/images/buttons/placeholder_buttondown.png").convert_alpha()
confirm_img = pygame.image.load("assets/images/buttons/confirm.png").convert_alpha()
confirmdown_img = pygame.image.load("assets/images/buttons/confirmdown.png").convert_alpha()
unconfirm_img = pygame.image.load("assets/images/buttons/x.png").convert_alpha()
unconfirmdown_img = pygame.image.load("assets/images/buttons/xdown.png").convert_alpha()
back_img = pygame.image.load("assets/images/buttons/back.png").convert_alpha()
backdown_img = pygame.image.load("assets/images/buttons/backdown.png").convert_alpha()
shapes_img = pygame.image.load("assets/images/buttons/shapes.png").convert_alpha()
shapesdown_img = pygame.image.load("assets/images/buttons/shapesdown.png").convert_alpha()
colours_img = pygame.image.load("assets/images/buttons/colours.png").convert_alpha()
coloursdown_img = pygame.image.load("assets/images/buttons/coloursdown.png").convert_alpha()
alphabet_img = pygame.image.load("assets/images/buttons/alphabet.png").convert_alpha()
alphabetdown_img = pygame.image.load("assets/images/buttons/alphabetdown.png").convert_alpha()
power_img = pygame.image.load("assets/images/buttons/power.png").convert_alpha()
powerdown_img = pygame.image.load("assets/images/buttons/powerdown.png").convert_alpha()
emptyslot1_img = pygame.image.load("assets/images/buttons/emptyslot1.png").convert_alpha()
emptyslot1down_img = pygame.image.load("assets/images/buttons/emptyslot1down.png").convert_alpha()
emptyslot2_img = pygame.image.load("assets/images/buttons/emptyslot2.png").convert_alpha()
emptyslot2down_img = pygame.image.load("assets/images/buttons/emptyslot2down.png").convert_alpha()
emptyslot3_img = pygame.image.load("assets/images/buttons/emptyslot3.png").convert_alpha()
emptyslot3down_img = pygame.image.load("assets/images/buttons/emptyslot3down.png").convert_alpha()
slot1_img = pygame.image.load("assets/images/buttons/slot1.png").convert_alpha()
slot1down_img = pygame.image.load("assets/images/buttons/slot1down.png").convert_alpha()
slot2_img = pygame.image.load("assets/images/buttons/slot2.png").convert_alpha()
slot2down_img = pygame.image.load("assets/images/buttons/slot2down.png").convert_alpha()
slot3_img = pygame.image.load("assets/images/buttons/slot3.png").convert_alpha()
slot3down_img = pygame.image.load("assets/images/buttons/slot3down.png").convert_alpha()
save_img = pygame.image.load("assets/images/buttons/save.png").convert_alpha()
savedown_img = pygame.image.load("assets/images/buttons/savedown.png").convert_alpha()
delete1_img = pygame.image.load("assets/images/buttons/delete1.png").convert_alpha()
delete1down_img = pygame.image.load("assets/images/buttons/delete1down.png").convert_alpha()
delete2_img = pygame.image.load("assets/images/buttons/delete2.png").convert_alpha()
delete2down_img = pygame.image.load("assets/images/buttons/delete2down.png").convert_alpha()
delete3_img = pygame.image.load("assets/images/buttons/delete3.png").convert_alpha()
delete3down_img = pygame.image.load("assets/images/buttons/delete3down.png").convert_alpha()
play1_img = pygame.image.load("assets/images/buttons/play1.png").convert_alpha()
play1down_img = pygame.image.load("assets/images/buttons/play1down.png").convert_alpha()
play2_img = pygame.image.load("assets/images/buttons/play2.png").convert_alpha()
play2down_img = pygame.image.load("assets/images/buttons/play2down.png").convert_alpha()
play3_img = pygame.image.load("assets/images/buttons/play3.png").convert_alpha()
play3down_img = pygame.image.load("assets/images/buttons/play3down.png").convert_alpha()

#shapes
circle_img = pygame.image.load("assets/images/shapes/circleplaceholder.png").convert_alpha()

#utility
textframe_original = pygame.image.load("assets/images/util/textframe.png").convert_alpha()
textinputframe_original = pygame.image.load("assets/images/util/textinputframe.png").convert_alpha()

#utility scaling
textframe = pygame.transform.scale(textframe_original, (int(textframe_original.get_width() * 0.33), int(textframe_original.get_height() * 0.33))).convert_alpha()
textframe_rect = textframe.get_rect()
textframe2 = pygame.transform.scale(textframe_original, (int(textframe_original.get_width() * 0.34), int(textframe_original.get_height() * 0.23))).convert_alpha()
textframe2_rect = textframe2.get_rect()
textinputframe = pygame.transform.scale(textinputframe_original, (int(textinputframe_original.get_width() * 0.33), int(textinputframe_original.get_height() * 0.33))).convert_alpha()
textinputframe_rect = textinputframe.get_rect()
emptyslot1_scaled = pygame.transform.scale(emptyslot1_img, (int(emptyslot1_img.get_width() * 0.65), int(emptyslot1_img.get_height() * 0.65))).convert_alpha()
emptyslot1_scaled_rect = emptyslot1_scaled.get_rect()
emptyslot2_scaled = pygame.transform.scale(emptyslot2_img, (int(emptyslot2_img.get_width() * 0.65), int(emptyslot2_img.get_height() * 0.65))).convert_alpha()
emptyslot2_scaled_rect = emptyslot2_scaled.get_rect()
emptyslot3_scaled = pygame.transform.scale(emptyslot3_img, (int(emptyslot3_img.get_width() * 0.65), int(emptyslot3_img.get_height() * 0.65))).convert_alpha()
emptyslot3_scaled_rect = emptyslot3_scaled.get_rect()
emptyslot1down_scaled = pygame.transform.scale(emptyslot1down_img, (int(emptyslot1down_img.get_width() * 0.65), int(emptyslot1down_img.get_height() * 0.65))).convert_alpha()
emptyslot1down_scaled_rect = emptyslot1down_scaled.get_rect()
emptyslot2down_scaled = pygame.transform.scale(emptyslot2down_img, (int(emptyslot2down_img.get_width() * 0.65), int(emptyslot2down_img.get_height() * 0.65))).convert_alpha()
emptyslot2down_scaled_rect = emptyslot2down_scaled.get_rect()
emptyslot3down_scaled = pygame.transform.scale(emptyslot3down_img, (int(emptyslot3down_img.get_width() * 0.65), int(emptyslot3down_img.get_height() * 0.65))).convert_alpha()
emptyslot3down_scaled_rect = emptyslot3down_scaled.get_rect()
slot1_scaled = pygame.transform.scale(slot1_img, (int(slot1_img.get_width() * 0.65), int(slot1_img.get_height() * 0.65))).convert_alpha()
slot1_scaled_rect = slot1_scaled.get_rect()
slot2_scaled = pygame.transform.scale(slot2_img, (int(slot2_img.get_width() * 0.65), int(slot2_img.get_height() * 0.65))).convert_alpha()
slot2_scaled_rect = slot2_scaled.get_rect()
slot3_scaled = pygame.transform.scale(slot3_img, (int(slot3_img.get_width() * 0.65), int(slot3_img.get_height() * 0.65))).convert_alpha()
slot3_scaled_rect = slot3_scaled.get_rect()
slot1down_scaled = pygame.transform.scale(slot1down_img, (int(slot1down_img.get_width() * 0.65), int(slot1down_img.get_height() * 0.65))).convert_alpha()
slot1down_scaled_rect = slot1down_scaled.get_rect()
slot2down_scaled = pygame.transform.scale(slot2down_img, (int(slot2down_img.get_width() * 0.65), int(slot2down_img.get_height() * 0.65))).convert_alpha()
slot2down_scaled_rect = slot2down_scaled.get_rect()
slot3down_scaled = pygame.transform.scale(slot3down_img, (int(slot3down_img.get_width() * 0.65), int(slot3down_img.get_height() * 0.65))).convert_alpha()
slot3down_scaled_rect = slot3down_scaled.get_rect()